### ISSUE TITLE
Cannot access to console

### ISSUE THREAD

**Issue by CloudHuang** [jboss-switchyard/console#40]
I have deployed the switchyard console war to JBoss EAP 6.2.4 but actually cannot open it in browser.
Also I tried to deploy the console to Tomcat 7, still cannot open it in browser.

As I cannot find any info about how to deploy the console in JBoss/Tomcat( maybe not support ), so I just do the normal web deploy.

**Comment by cunningt** [comment]
Please start a thread detailing the steps you took, JDK/maven you used, and error you see here -
 
https://developer.jboss.org/en/switchyard?view=discussions
